### ISSUE TITLE
HTTP ERROR 404

### ISSUE THREAD

**Issue by antoniomorais360** [igniterealtime/openfire-emailListener-plugin#3]
I am using Openfire 4.4.4

I installed the Email Listener version 1.2.1
https://www.igniterealtime.org/projects/openfire/plugins/1.2.1-SNAPSHOT/emailListener.jar?snapshot=20191213.161312-194

But when I tried to configure in Server Settings / Email Listener I get Error 404.

**Comment by antoniomorais360** [comment]
The log says:
at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
java.lang.ClassNotFoundException: org.jivesoftware.openfire.plugin.EmailListenerPlugin
2019.12.14 18:58:39 org.jivesoftware.openfire.container.PluginManager - An exception occurred while loading plugin 'emaillistener':
at java.lang.Thread.run(Thread.java:834) [?:?]
